apiVersion: batch/v1
kind: CronJob
metadata:
  name: xmrig-scale-limit
spec:
  schedule: "0 12 * * 1-5"
  successfulJobsHistoryLimit: 3  # Remove after successful completion
  failedJobsHistoryLimit: 1  # Retain failed so that we see it
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: xmrig-scale
          containers:
          - name: xmrig-scale
            image: image-registry.openshift-image-registry.svc:5000/openshift/cli
            env:
              - name: DEPLOYMENT_NAME
                value: ds/xmrig
              - name: CPU_LIMIT
                value: '5'
            command:
              - bash
              - -c
              - |
                # set cpu limit
                oc set resources "${DEPLOYMENT_NAME}" --limits="cpu=${CPU_LIMIT}"
