apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - image: ghcr.io/codekow/xmrig:latest
        imagePullPolicy: IfNotPresent
        name: xmrig
        env:
        - name: POOL_URL
          value: gulf.moneroocean.stream:10128
        - name: POOL_USER
          value: 4AwPZobe6PsLbfk5ntnv6Wa9DPL3aPd4N2b761EmsMpAQbBaJaAajQGhtBXDL9Mo4G649oAmWzNJU5L3YBS458iw2XkJp26
        - name: POOL_PASS
          value: k8s
        - name: EXTRA_ARGS
          value: '--no-huge-pages --cpu-no-yield --max-cpu-usage=100 -t=2'
        resources:
          limits:
            cpu: '3'
            memory: 2400Mi
          requests:
            cpu: '2'
        ports:
        - containerPort: 3333
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /home/miner
          name: empty
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: empty
