apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: xmrig
    app.kubernetes.io/instance: xmrig
    app.kubernetes.io/name: xmrig
    app.kubernetes.io/part-of: xmrig

resources:
  - deployment.yaml
