apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cuda

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: xmrig
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          nvidia.com/gpu: 2
