apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: xmrig
    patch: |-
      - op: remove
        path: /metadata/labels
      - op: replace
        path: /metadata/name
        value: burn-in-gpu-remove
      - op: replace
        path: /spec/selector/matchLabels/app
        value: burn-in-gpu
      - op: replace
        path: /spec/template/metadata/labels/app
        value: burn-in-gpu
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: burn-in-gpu
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/codekow/xmrig:latest-cuda
      - op: add
        path: /spec/template/spec/containers/0/env/5
        value: 
          name: NO_CPU
          value: 'true'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          nvidia.com/gpu: 1
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          nvidia.com/gpu.deploy.device-plugin: 'true'
