---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig-proxy
    app.kubernetes.io/component: xmrig-proxy
    app.kubernetes.io/instance: xmrig-proxy
    app.kubernetes.io/name: xmrig-proxy
    app.kubernetes.io/part-of: xmrig-proxy
  name: xmrig-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig-proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xmrig-proxy
    spec:
      containers:
      - image: ghcr.io/codekow/xmrig-proxy:latest
        imagePullPolicy: IfNotPresent
        name: xmrig-proxy
        env:
        - name: POOL_URL
          value: pool.supportxmr.com:3333
        - name: POOL_USER
          value: 4AwPZobe6PsLbfk5ntnv6Wa9DPL3aPd4N2b761EmsMpAQbBaJaAajQGhtBXDL9Mo4G649oAmWzNJU5L3YBS458iw2XkJp26
        - name: POOL_PASS
          value: openshift-proxy
        - name: EXTRA_ARGS
          value: '--verbose --no-color'
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 3333
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /home/miner
          name: empty
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: empty
