apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig-direct
    app.kubernetes.io/component: xmrig-direct
    app.kubernetes.io/instance: xmrig-direct
    app.kubernetes.io/name: xmrig-direct
    app.kubernetes.io/part-of: xmrig-direct
  name: xmrig-direct-miner
spec:
  replicas: 10
  selector:
    matchLabels:
      app: xmrig-direct-miner
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xmrig-direct-miner
    spec:
      containers:
      - image: ghcr.io/codekow/xmrig:latest
        imagePullPolicy: IfNotPresent
        name: xmrig-direct-miner
        env:
        - name: POOL_URL
          value: gulf.moneroocean.stream:443
        - name: POOL_USER
          value: 4AwPZobe6PsLbfk5ntnv6Wa9DPL3aPd4N2b761EmsMpAQbBaJaAajQGhtBXDL9Mo4G649oAmWzNJU5L3YBS458iw2XkJp26
        - name: POOL_PASS
          value: openshift-direct
        - name: EXTRA_ARGS
          value: '--no-huge-pages --cpu-no-yield --max-cpu-usage=100 -t=1 --no-color'
        resources:
          limits:
            cpu: '1'
            memory: 2400Mi
          requests:
            cpu: '1'
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /home/miner
          name: empty
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: empty
