apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-burn-in-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: >-
              data:text/plain;charset=utf-8;base64,YXBpVmVyc2lvbjogdjEKa2luZDogUG9kCm1ldGFkYXRhOgogIGxhYmVsczoKICAgIGFwcDogYnVybi1pbgogIG5hbWU6IGJ1cm4taW4KICBuYW1lc3BhY2U6IGRlZmF1bHQKc3BlYzoKICBjb250YWluZXJzOgogIC0gaW1hZ2U6IGdoY3IuaW8vY29kZWtvdy94bXJpZzpsYXRlc3QKICAgIG5hbWU6IGJ1cm4taW4KICAgIHJlc291cmNlczoKICAgICAgbGltaXRzOgogICAgICAgIG1lbW9yeTogMjQwME1pCiAgICAgIHJlcXVlc3RzOgogICAgICAgIG1lbW9yeTogMjQwME1pCiAgICBlbnY6CiAgICAgIC0gbmFtZTogUE9PTF9VUkwKICAgICAgICB2YWx1ZTogcHJveHkuYnVybi1pbi5zdmMuY2x1c3Rlci5sb2NhbDozMzMzCiAgICAgIC0gbmFtZTogRVhUUkFfQVJHUwogICAgICAgIHZhbHVlOiAnLS1jcHUtcHJpb3JpdHk9MCcKICAgIHNlY3VyaXR5Q29udGV4dDoKICAgICAgcHJpdmlsZWdlZDogdHJ1ZQogIHJlc3RhcnRQb2xpY3k6IEFsd2F5cwogIGhvc3ROZXR3b3JrOiB0cnVlCg==
          mode: 420
          overwrite: true
          path: /etc/kubernetes/manifests/burn-in-pod.yaml
