apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xmrig
  name: xmrig
spec:
  containers:
  - image: ghcr.io/codekow/xmrig:latest
    name: container
    resources:
      limits:
        memory: 2400Mi
      requests:
        memory: 2400Mi
    env:
      - name: EXTRA_ARGS
        value: '--asm=none --no-huge-pages --cpu-no-yield --max-cpu-usage=100'
    securityContext:
      privileged: false
  restartPolicy: Never

