apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment
  - xmrig-proxy-svc.yaml

patches:
  - target:
      group: apps
      kind: Deployment
      name: xmrig
    patch: |-
      - op: remove
        path: /metadata/labels
      - op: replace
        path: /metadata/name
        value: xmrig-proxy
      - op: replace
        path: /spec/selector/matchLabels/app
        value: xmrig-proxy
      - op: replace
        path: /spec/template/metadata/labels/app
        value: xmrig-proxy
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: xmrig-proxy
      - op: replace
        path: /spec/template/spec/containers/0/env/2
        value:
          name: POOL_PASS
          value: k8s-proxy
      - op: replace
        path: /spec/template/spec/containers/0/env/3
        value:
          name: EXTRA_ARGS
          value: ''
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/codekow/xmrig-proxy:latest
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
