apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../burn-in

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: xmrig
    patch: |-
      # - op: remove
      #   path: /metadata/labels
      - op: replace
        path: /metadata/name
        value: burn-in-cuda-remove
      - op: replace
        path: /spec/selector/matchLabels/app
        value: burn-in-cuda
      - op: replace
        path: /spec/template/metadata/labels/app
        value: burn-in-cuda
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: burn-in-cuda
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/codekow/xmrig:6.22.2-cuda
      - op: replace
        path: /spec/template/spec/containers/0/env/3
        value:
          name: POOL_PASS
          value: k8s-gpu
      - op: replace
        path: /spec/template/spec/containers/0/env/4
        value:
          name: EXTRA_ARGS
          value: '--no-huge-pages --cpu-no-yield --max-cpu-usage=100 --no-cpu'
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          nvidia.com/gpu: 1
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          nvidia.com/gpu.deploy.device-plugin: 'true'
