apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../burn-in

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: xmrig
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: '2'
          memory: 2400Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: '2'
          memory: 2400Mi
