apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: xmrig
    patch: |-
      - op: remove
        path: /metadata/labels
      - op: replace
        path: /metadata/name
        value: burn-in-hugepages-2m-remove
      - op: replace
        path: /spec/selector/matchLabels/app
        value: burn-in-hugepages-2m
      - op: replace
        path: /spec/template/metadata/labels/app
        value: burn-in-hugepages-2m
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: burn-in-hugepages-2m
      - op: replace
        path: /spec/template/spec/containers/0/env/3
        value: 
          name: POOL_PASS
          value: hugepages-2m
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            hugepages-2Mi: 2400Mi
            memory: 64Mi
          requests:
            hugepages-2Mi: 2400Mi
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/os: linux
          node-role.kubernetes.io/worker-hp-2m: ''
