---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-compute
spec:
  hard:
    # requests.cpu: '1'
    # requests.memory: 1Gi
    limits.cpu: '32'
    limits.memory: 128Gi
    requests.nvidia.com/gpu: '0'
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-objects
spec:
  hard:
    count/sealedsecrets.bitnami.com: '0'
    count/cronjobs.batch: '4'
    count/daemonsets.apps: '0'
