kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: xmrig
  labels:
    app: xmrig
    app.kubernetes.io/component: xmrig
    app.kubernetes.io/instance: xmrig
    app.kubernetes.io/name: xmrig
    app.kubernetes.io/part-of: xmrig
spec:
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      volumes:
        - name: empty
          emptyDir: {}
      containers:
        - resources:
            limits:
              # cpu: '5'
              memory: 2400Mi
            requests:
              memory: 2400Mi
          name: xmrig
          env:
            - name: DONATE_LEVEL
              value: '0'
            - name: POOL_URL
              value: 'pool.supportxmr.com:3333'
            - name: POOL_USER
              value: 4AwPZobe6PsLbfk5ntnv6Wa9DPL3aPd4N2b761EmsMpAQbBaJaAajQGhtBXDL9Mo4G649oAmWzNJU5L3YBS458iw2XkJp26
            - name: POOL_PASS
              value: openshift-direct
            - name: EXTRA_ARGS
              value: '--asm=none --no-huge-pages --cpu-no-yield --max-cpu-usage=100 --no-color'
          securityContext:
            privileged: false
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: empty
              mountPath: /home/miner/config
          image: image-registry.openshift-image-registry.svc:5000/burn-in/xmrig:latest
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      # maxSurge: 3
  revisionHistoryLimit: 3
