---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: alpine
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "3"
    from:
      kind: DockerImage
      name: docker.io/alpine
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Local
  - name: latest
    from:
      kind: ImageStreamTag
      name: '3'
    importPolicy: {}
    referencePolicy:
      type: Local
