apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: xmrig
    app.kubernetes.io/part-of: xmrig
  name: xmrig-proxy
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: ghcr.io/codekow/xmrig-proxy:latest
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
