---
kind: Template
apiVersion: template.openshift.io/v1
labels:
  template: xmrig-direct
  app.kubernetes.io/part-of: xmrig
metadata:
  name: xmrig-direct
  annotations:
    openshift.io/display-name: XMRig
    description: Run xmrig
    iconClass: icon-openshift
    tags: xmrig
    openshift.io/documentation-url: "https://github.com/codekow/container-xmrig"
    openshift.io/support-url: "https://github.com/codekow/container-xmrig/issues"
    template.openshift.io/bindable: "false"
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  required: true
  value: xmrig-direct
- name: DEPLOY_MEM_LIMIT
  displayName: Deploy Memory Limit
  value: 2400Mi
  required: true
  description: This is the right size for 1 CPU and thread
- name: DEPLOY_CPU_LIMIT
  displayName: Deploy CPU Limit
  value: '1'
  required: true
  description: This is using 1 CPU and 1 thread
- name: DOCKER_IMAGE_BASE
  description: "Base docker URI for building"
  value: "ghcr.io/codekow/xmrig"
- name: DOCKER_IMAGE_TAG
  description: "Base docker URI for building"
  value: "latest"
- name: POOL_URL
  value: pool.supportxmr.com:3333
- name: POOL_USER
  value: 42Fx7FEPRdUjDYckqrW6fqF4zwDD332uLTvDTpRv2KHnHsV2LWv1NVA4SjJwnfik8BFyD8Cx3yJxETVEFrKCehoMPxdum8g
- name: POOL_PASS
  value: openshift-direct
- name: DONATE_LEVEL
  value: '1'
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-miner
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: ${DOCKER_IMAGE_BASE}:${DOCKER_IMAGE_TAG}
        name: ${DOCKER_IMAGE_TAG}
        importPolicy:
          scheduled: true
      - from:
          kind: ImageStreamTag
          name: ${DOCKER_IMAGE_TAG}
        name: "stable"
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-miner
  spec:
    replicas: 10
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}-miner
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}-miner
      spec:
        containers:
        - image: ${APPLICATION_NAME}-miner:latest
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}-miner
          env:
          - name: DONATE_LEVEL
            value: "${DONATE_LEVEL}"
          - name: POOL_URL
            value: "${POOL_URL}"
          - name: POOL_USER
            value: "${POOL_USER}"
          - name: POOL_PASS
            value: "${POOL_PASS}"
          - name: EXTRA_ARGS
            value: '--asm=none --no-huge-pages --cpu-no-yield --max-cpu-usage=100 -t=1 --no-color'
          resources:
            limits:
              cpu: "${DEPLOY_CPU_LIMIT}"
              memory: "${DEPLOY_MEM_LIMIT}"
            requests:
              cpu: "${DEPLOY_CPU_LIMIT}"
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: /home/miner
            name: empty
        restartPolicy: Always
        volumes:
        - emptyDir: {}
          name: empty
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}-miner
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-miner:latest
      type: ImageChange
    - type: ConfigChange
