kind: Template
apiVersion: template.openshift.io/v1
labels:
  template: xmrig
  app.kubernetes.io/part-of: xmrig
metadata:
  name: xmrig
  annotations:
    openshift.io/display-name: XMRig
    description: Build xmrig inside a container
    iconClass: icon-openshift
    tags: xmrig
    openshift.io/documentation-url: "https://github.com/codekow/container-xmrig"
    openshift.io/support-url: "https://github.com/codekow/container-xmrig/issues"
    template.openshift.io/bindable: "false"
parameters:
- name: APPLICATION_NAME
  displayName: Application Name
  required: true
  value: xmrig
- name: BUILD_MEM_LIMIT
  displayName: Build Memory Limit
  value: 256Mi
  required: true
  description: Consider the pod quota limits
- name: BUILD_CPU_LIMIT
  displayName: Build CPU Limit
  value: 400m
  required: true
  description: Consider the pod quota limits
- name: CUSTOM_PROXY
  displayName: Proxy server
  value: ""
- name: NO_PROXY
  value: ""
- name: BUILD_DEPLOY_TOKEN_USERNAME
  description: "Username to allow cloning of private repos"
  displayName: "GIT Username"
- name: BUILD_DEPLOY_TOKEN_PASSWORD
  description: "Username to allow cloning of private repos"
  displayName: "GIT Password"
- name: CONTEXT_DIR
  description: "Build Source Files Directory"
  displayName: "Context Directory"
  value: xmrig
- name: BUILD_REF
  description: "Branch Name to build from (default: main)"
  value: main
- name: BUILD_URL
  description: "URL to git repo"
  value: "https://github.com/codekow/container-xmrig.git"
- name: DOCKER_IMAGE_BASE
  description: "Base docker URI for building"
  value: "docker.io/alpine"
- name: DOCKER_IMAGE_TAG
  description: "Base docker URI for building"
  value: "3"
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      build: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: true
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    annotations:
      docker.io/source: "docker.io/alpine:${DOCKER_IMAGE_TAG}"
    labels:
      build: ${APPLICATION_NAME}
    name: alpine
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: ${DOCKER_IMAGE_BASE}:${DOCKER_IMAGE_TAG}
        name: ${DOCKER_IMAGE_TAG}
      - from:
          kind: ImageStreamTag
          name: ${DOCKER_IMAGE_TAG}
        name: "latest"
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-alpine
    annotations:
      app.openshift.io/vcs-ref: ${BUILD_REF}
      app.openshift.io/vcs-uri: ${BUILD_URL}
  spec:
    resources:
      limits:
        memory: ${BUILD_MEM_LIMIT}
        cpu: ${BUILD_CPU_LIMIT}
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${BUILD_URL}
        ref: ${BUILD_REF}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: "alpine:latest"
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
