name: Check Spelling
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.2
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.46.0
